# 設置頭像
avatar:
  type: img # 設置類型為圖片
  path: /assets/img/IMG_5430.jpeg # 您圖片在 assets/img/ 下的具體路徑
  alt: "KwanLam's Daily" # 頭像的替代文本，建議與您的部落格標題一致

theme: jekyll-theme-chirpy
lang: en
timezone: Asia/Hong_Kong

title: "KwanLam's Daily"
tagline: "音樂、數位與生活的碎片"
description: "這是一個關於音樂與數位的個人部落格"
url: 'https://kwanlam.cc'

github:
  username: kwanlam08

social:
  name: Kwanlam Ng
  email: me@kwanlam.cc
  links:
    - https://github.com/Kwanlam08

paginate: 10
baseurl: ""

# 保持默認配置
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
