title: KwanLam's Daily
tagline: 音樂、數位與生活的碎片
avatar: /assets/img/posts/IMG_2504.jpeg
description: 這是一個關於音樂與數位的個人部落格
defaults:
  - values:
      permalink: /posts/:title/
      toc: true
      comments: true
      layout: post
    scope:
      type: posts
      path: ''
  - values:
      permalink: /:title/
      layout: page
    scope:
      type: tabs
      path: ''
collections:
  tabs:
    sort_by: order
    output: true
kramdown:
  syntax_highlighter: rouge
  footnote_backlink: '&#8617;&#xfe0e;'
github:
  username: kwanlam08
theme: jekyll-theme-chirpy
lang: en
timezone: Asia/Hong_Kong
url: https://kwanlam.cc
social:
  name: Kwanlam Ng
  email: me@kwanlam.cc
  links:
    - https://github.com/Kwanlam08
paginate: 10
baseurl: ''
