backend:
  name: github
  repo: Kwanlam08/Kwanlam-sBlog
  branch: main
  base_url: "https://cms-auth.junlinwu0811.workers.dev"

# 讓後台自動處理圖片路徑
media_folder: "assets/img/posts"
public_folder: "/assets/img/posts"

collections:
  - name: "posts"
    label: "發佈新文章"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "文章標題 (Title)", name: "title", widget: "string"}
      - {label: "發佈時間 (Date)", name: "date", widget: "datetime"}
      - {label: "分類 (Categories)", name: "categories", widget: "list", default: ["生活", "隨筆"]}
      - {label: "標籤 (Tags)", name: "tags", widget: "list", default: ["日常"]}
      - label: "封面大圖 (Banner，若無可留空)"
        name: "image"
        widget: "object"
        required: false
        fields:
          - {label: "點擊上傳圖片", name: "path", widget: "image", required: false}
          - {label: "圖片描述", name: "alt", widget: "string", required: false}
      - {label: "在這裡寫正文...", name: "body", widget: "markdown"}
