backend:
  name: github
  # ⚠️ 注意：這裡的用戶名和倉庫名必須與你 GitHub 上的完全一致
  repo: Kwanlam08/Kwanlam-sBlog
  branch: main # 如果你的預設分支叫 master，請改成 master

# 讓你上傳的圖片自動存進這個資料夾
media_folder: "assets/img/posts"
public_folder: "/assets/img/posts"

collections:
  - name: "posts"
    label: "發佈新文章"
    folder: "_posts"
    create: true
    # 自動幫你生成 "2026-03-29-標題.md" 這種標準檔名
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "文章標題 (Title)", name: "title", widget: "string"}
      - {label: "發佈時間 (Date)", name: "date", widget: "datetime"}
      - {label: "分類 (Categories)", name: "categories", widget: "list", default: ["生活", "隨筆"]}
      - {label: "標籤 (Tags)", name: "tags", widget: "list", default: ["日常"]}
      - label: "封面大圖 (Banner，若無可留空)"
        name: "image"
        widget: "object"
        required: false
        fields:
          - {label: "點擊上傳圖片", name: "path", widget: "image", required: false}
          - {label: "圖片描述", name: "alt", widget: "string", required: false}
      - {label: "在這裡寫正文...", name: "body", widget: "markdown"}
